#!/usr/bin/env bash

sudo chattr -i /etc/resolv.conf

sudo rm /etc/resolv.conf

sudo systemctl disable --now systemd-resolved

echo "nameserver 127.0.0.1" | sudo tee /etc/resolv.conf >/dev/null

sudo chattr +i /etc/resolv.conf

echo "DNS configuration updated successfully."
echo "Disabled systemd-resolved."
